version: '3'

services:
  minio:
    image: minio/minio:latest
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - minionetwork
    environment:
      MINIO_ROOT_USER: minioadm # Modificar
      MINIO_ROOT_PASSWORD: g#9umqCZ6tXSEP # Modificar
    command: server /data --console-address ":9001"

networks:
  minionetwork:
    driver: bridge

volumes:
  data1-1:
  data1-2:
